//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-07-16 09:42:06 by yongyi
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace XSchool.GCenter.Model
{	

	public class KpiTemplateAuditRecord
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 考核模板记录Id
		/// </summary>		
		public int KpiTemplateRecordId { get; set; }
		
		/// <summary>
		/// 当前步骤
		/// </summary>		
		public int Steps { get; set; }
		
		/// <summary>
		/// 公司Id
		/// </summary>		
		public int CompanyId { get; set; }
		
		/// <summary>
		/// 公司名称
		/// </summary>		
		public string CompanyName { get; set; }
		
		/// <summary>
		/// 部门Id
		/// </summary>		
		public int DptId { get; set; }
		
		/// <summary>
		/// 部门名称
		/// </summary>		
		public string DptName { get; set; }
		
		/// <summary>
		/// 职位Id
		/// </summary>		
		public int JobId { get; set; }
		
		/// <summary>
		/// 职位名称
		/// </summary>		
		public string JobName { get; set; }
		 
    }
}

