//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-07-18 20:05:49 by yongyi
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace XSchool.GCenter.Model
{	

	public class KpiTemplateRecord
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 考核类型，1-部门，2-人员
		/// </summary>		
		public int KpiType { get; set; }
		
		/// <summary>
		/// 所属考核方案Id
		/// </summary>		
		public int KpiId { get; set; }
		
		/// <summary>
		/// 所属考核方案
		/// </summary>		
		public string KpiName { get; set; }
		
		/// <summary>
		/// 公司Id
		/// </summary>		
		public int CompanyId { get; set; }
		
		/// <summary>
		/// 公司名称
		/// </summary>		
		public string CompanyName { get; set; }
		
		/// <summary>
		/// 部门Id
		/// </summary>		
		public int DptId { get; set; }
		
		/// <summary>
		/// 部门名称
		/// </summary>		
		public string DptName { get; set; }
		
		/// <summary>
		/// 人员Id
		/// </summary>		
		public int EmployeeId { get; set; }
		
		/// <summary>
		/// 人员名称
		/// </summary>		
		public string UserName { get; set; }
		
		/// <summary>
		/// 考核内容
		/// </summary>		
		public string Content { get; set; }
		
		/// <summary>
		/// 审核人
		/// </summary>		
		public string Audits { get; set; }
		 
    }
}

