//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-07-05 18:58:15 by yongyi
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace XSchool.WorkFlow.Model
{	

	public class SubjectRule
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 流程id
		/// </summary>		
		public int SubjectId { get; set; }
		
		/// <summary>
		/// 业务类型 1流程管理可见者，2流程管理节点人员
		/// </summary>		
		public int BusinessType { get; set; }
		
		/// <summary>
		/// 公司id
		/// </summary>		
		public int? CompanyId { get; set; }
		
		/// <summary>
		/// 部门id
		/// </summary>		
		public int? DepId { get; set; }
		
		/// <summary>
		/// 人员id
		/// </summary>		
		public int? UserId { get; set; }
		
		/// <summary>
		/// 职位id
		/// </summary>		
		public int? JobDepId { get; set; }
		
		/// <summary>
		/// 部门岗位id
		/// </summary>		
		public int? JobId { get; set; }
		 
    }
}

